spring:
  application:
    name: EUREKA-SERVER-REGISTRY

server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck: 
      enabled: true
        
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost      