spring:
  application:
    name: india-microservice
  
server:
  port: 8083
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  